# Using the latest Hugo image
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# Test stage to build the site
test:
  script:
    - hugo
  except:
    - main

# Pages stage to build and deploy to GitLab Pages
pages:
  script:
    - hugo --minify
  artifacts:
    paths:
      - public
  only:
    - main
