
title: Best Magisk Module
email: bestmagiskmodule@gmail.com
description: "Best Magisk Module"
baseurl: "/"
url: "https://bestmagiskmodule.github.io"
twitter_username: bestmagisk
github_username:  bestmagisk
author: bestmagisk

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
